/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DeviceDisplayMode = "mixup" | "playlist" | "screen";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
	string,
	bigint | number | string,
	bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MixupLayoutId =
	| "horizontal-halves"
	| "left-rail"
	| "quarters"
	| "top-banner"
	| "vertical-halves";

export type Numeric = ColumnType<string, number | string, number | string>;

export type RecipeType = "liquid" | "react";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
	accessToken: string | null;
	accessTokenExpiresAt: Timestamp | null;
	accountId: string;
	createdAt: Generated<Timestamp>;
	id: string;
	idToken: string | null;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	refreshTokenExpiresAt: Timestamp | null;
	scope: string | null;
	updatedAt: Timestamp;
	userId: string;
}

export interface Devices {
	api_key: string;
	/**
	 * Battery voltage in volts
	 */
	battery_voltage: Numeric | null;
	created_at: Generated<Timestamp | null>;
	current_playlist_index: Generated<number | null>;
	display_mode: Generated<DeviceDisplayMode | null>;
	/**
	 * Device firmware version
	 */
	firmware_version: string | null;
	friendly_id: string;
	/**
	 * Grayscale level (0-255, where 0 is full color and 255 is full grayscale)
	 */
	grayscale: Generated<number | null>;
	id: Generated<Int8>;
	last_refresh_duration: number | null;
	last_update_time: Timestamp | null;
	mac_address: string;
	mixup_id: string | null;
	/**
	 * TRMNL model name reported via the Model request header (e.g. og_plus, seeed_e1002, v2). Used to resolve render parameters from the local TRMNL models registry.
	 */
	model: string | null;
	name: string;
	next_expected_update: Timestamp | null;
	/**
	 * Optional palette override when the device model supports multiple palettes. NULL means use the model's first declared palette as default.
	 */
	palette_id: string | null;
	playlist_id: string | null;
	refresh_schedule: Json | null;
	/**
	 * WiFi signal strength in dBm
	 */
	rssi: number | null;
	screen: string | null;
	/**
	 * Screen height in pixels
	 */
	screen_height: Generated<number | null>;
	/**
	 * Screen orientation: portrait or landscape
	 */
	screen_orientation: Generated<string | null>;
	/**
	 * Screen width in pixels
	 */
	screen_width: Generated<number | null>;
	/**
	 * Quiet-hours end as minutes since midnight (TRMNL convention).
	 */
	sleep_end_time: number | null;
	/**
	 * Whether the device honors the configured quiet-hours window.
	 */
	sleep_mode_enabled: Generated<boolean>;
	/**
	 * Quiet-hours start as minutes since midnight (TRMNL convention).
	 */
	sleep_start_time: number | null;
	/**
	 * TRUE when the device sent the `temperature-profile: true` request header on its last /api/display call. NULL until the device has been seen.
	 */
	supports_temperature_profile: Generated<boolean | null>;
	/**
	 * Display tuning profile sent to the firmware in the /api/display response (default|a|b|c).
	 */
	temperature_profile: Generated<string>;
	timezone: Generated<string>;
	updated_at: Generated<Timestamp | null>;
	user_id: string | null;
}

export interface Logs {
	created_at: Generated<Timestamp | null>;
	friendly_id: string | null;
	id: Generated<Int8>;
	log_data: string;
}

export interface Mixups {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	layout_id: MixupLayoutId;
	name: string;
	updated_at: Generated<Timestamp | null>;
	user_id: string | null;
}

export interface MixupSlots {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	mixup_id: string | null;
	order_index: number;
	recipe_id: string | null;
	slot_id: string;
}

export interface PendingDeviceClaims {
	api_key: string;
	api_key_suffix: string;
	claim_hash: string;
	first_seen_at: Generated<Timestamp>;
	height: number | null;
	last_seen_at: Generated<Timestamp>;
	mac_address: string | null;
	model: string | null;
	width: number | null;
}

export interface PlaylistItems {
	created_at: Generated<Timestamp | null>;
	days_of_week: Json | null;
	duration: Generated<number>;
	end_time: string | null;
	id: Generated<string>;
	order_index: number;
	playlist_id: string | null;
	screen_id: string;
	start_time: string | null;
}

export interface PluginSettings {
	created_at: Generated<Timestamp | null>;
	fields: Generated<JsonObject>;
	icon_content_type: string | null;
	icon_url: string | null;
	id: Generated<Int8>;
	markup: Generated<JsonObject>;
	merge_variables: Generated<JsonObject>;
	name: string;
	plugin_id: number;
	read_only: Generated<boolean>;
	settings_yaml: string | null;
	strategy: string | null;
	updated_at: Generated<Timestamp | null>;
	user_id: string;
	uuid: string;
}

export interface Playlists {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	name: string;
	updated_at: Generated<Timestamp | null>;
	user_id: string | null;
}

export interface RecipeFiles {
	content: string;
	created_at: Generated<Timestamp | null>;
	filename: string;
	id: Generated<string>;
	recipe_id: string;
}

export interface Recipes {
	author: string | null;
	author_email: string | null;
	author_github: string | null;
	category: string | null;
	created_at: Generated<Timestamp | null>;
	description: string | null;
	id: Generated<string>;
	logo_url: string | null;
	metadata: Generated<JsonObject | null>;
	name: string;
	repo: string | null;
	screenshot_url: string | null;
	slug: string;
	type: RecipeType;
	updated_at: Generated<Timestamp | null>;
	user_id: string | null;
	version: string | null;
	zip_entry_path: string | null;
	zip_url: string | null;
}

export interface ScreenConfigs {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	/**
	 * JSON blob of screen parameters
	 */
	params: Generated<Json>;
	screen_id: string;
	updated_at: Generated<Timestamp | null>;
	user_id: string | null;
}

export interface Session {
	createdAt: Generated<Timestamp>;
	expiresAt: Timestamp;
	id: string;
	impersonatedBy: string | null;
	ipAddress: string | null;
	token: string;
	updatedAt: Timestamp;
	userAgent: string | null;
	userId: string;
}

export interface SystemLogs {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	level: string;
	message: string;
	metadata: string | null;
	source: string | null;
	trace: string | null;
}

export interface User {
	banExpires: Timestamp | null;
	banned: Generated<boolean | null>;
	banReason: string | null;
	createdAt: Generated<Timestamp>;
	email: string;
	emailVerified: boolean;
	id: string;
	image: string | null;
	name: string;
	role: Generated<string | null>;
	updatedAt: Generated<Timestamp>;
}

export interface Verification {
	createdAt: Generated<Timestamp>;
	expiresAt: Timestamp;
	id: string;
	identifier: string;
	updatedAt: Generated<Timestamp>;
	value: string;
}

export interface DB {
	account: Account;
	devices: Devices;
	logs: Logs;
	mixup_slots: MixupSlots;
	mixups: Mixups;
	pending_device_claims: PendingDeviceClaims;
	playlist_items: PlaylistItems;
	plugin_settings: PluginSettings;
	playlists: Playlists;
	recipe_files: RecipeFiles;
	recipes: Recipes;
	screen_configs: ScreenConfigs;
	session: Session;
	system_logs: SystemLogs;
	user: User;
	verification: Verification;
}
