/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/display": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Fetch the next screen */
		get: {
			parameters: {
				query?: never;
				header: {
					/** @description Device API Key (eg. abc-123) */
					"Access-Token": string;
					/** @description Device battery voltage (eg. 3.7) */
					"Battery-Voltage"?: number;
					/** @description Device percent charged (eg. 69.4) */
					"Percent-Charged"?: number;
					/** @description Number of batteries in device (e.g. 1-2) */
					"Battery-Count"?: number;
					/** @description Whether device is plugged into power (eg. true) */
					"Battery-Charging"?: number;
					/** @description Quality of battery (eg. -1-100) */
					"Battery-Health"?: number;
					/** @description Battery current (eg. -1-N) */
					"Battery-Current"?: number;
					/** @description Battery temperature in celsius (eg. -1-N) */
					"Battery-Temp"?: number;
					/** @description Ratio of current / max capacity (eg. -1/-1 in fault case) */
					"Battery-Capacity"?: number;
					/** @description Device firmware version (eg. 0.0.1) */
					"FW-Version"?: string;
					/** @description Device RSSI (eg. -69) */
					RSSI?: number;
					/** @description Device screen height (eg. 480) */
					Height?: string;
					/** @description Device screen width (eg. 800) */
					Width?: string;
					/** @description Device special function (eg. true) */
					"Special-Function"?: boolean;
					/** @description Encode image function (eg. true) */
					BASE64?: boolean;
					/** @description Environmental sensor data */
					Sensors?: string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @example 200 */
							status?: number;
							/** @example https://trmnl.com/images/system_screens/setup_logo/og_plus.png */
							image_url?: string | null;
							/** @example setup-logo.bmp */
							filename?: string | null;
							/** @example 300 */
							refresh_rate?: number;
							/** @example false */
							reset_firmware?: boolean;
							/** @example false */
							update_firmware?: boolean;
							/** @example https://trmnl.com/firmware/1.0.0.bin */
							firmware_url?: string | null;
							/** @example identify */
							special_function?: string;
							/** @example identify */
							action?: string | null;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/display/current": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Fetch the current screen */
		get: {
			parameters: {
				query?: never;
				header: {
					/** @description Device API Key (eg. abc-123) */
					"Access-Token": string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @example 200 */
							status?: number;
							/** @example 300 */
							refresh_rate?: number;
							/** @example https://trmnl.com/images/system_screens/setup_logo/og_plus.png */
							image_url?: string | null;
							/** @example setup-logo.bmp */
							filename?: string | null;
							/** @example 2023-01-01T00:00:00Z */
							rendered_at?: string | null;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/log": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Log with logs[] (array) */
		post: {
			parameters: {
				query?: never;
				header: {
					/** @description Device API Key (eg. abc-123) */
					"Access-Token": string;
				};
				path?: never;
				cookie?: never;
			};
			/** @description An array of log entries. Each entry can be any JSON type: string, object, etc. */
			requestBody: {
				content: {
					"application/json": {
						logs: unknown[];
					};
				};
			};
			responses: {
				/** @description Logs created when ignore_log_messages is not set */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/setup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Set up device
		 * @description Please note that the returned `status` JSON value may NOT always equal the HTTP status code. Notably, if a device MAC address is not found,
		 *     then the HTTP status code will be 200 but the `status` code in the response will be 404.
		 */
		get: {
			parameters: {
				query?: never;
				header: {
					/** @description Device MAC Address (eg. 41:B4:10:39:A1:24) */
					ID: string;
					/** @description DEVICE_MODEL from firmware definitions */
					Model: string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @example 200 */
							status?: number;
							/** @example abc-123 */
							api_key?: string | null;
							/** @example ABC-123 */
							friendly_id?: string | null;
							/** @example https://trmnl.com/images/system_screens/setup_logo/og_plus.png */
							image_url?: string | null;
							/** @example Register at trmnl.com/start with Device ID 'ABC-123' */
							message?: string;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/categories": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all plugin categories
		 * @description Returns a list of approved plugin categories.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @example 200 */
							status?: number;
							/**
							 * @example [
							 *       "life",
							 *       "marketing",
							 *       "ecommerce"
							 *     ]
							 */
							data?: string[];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/ips": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all TRMNL server IP addresses
		 * @description Returns a list of public IP addresses for all TRMNL core servers.
		 *
		 *     Plugin poll requests will only originate from these IPs.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: {
								ipv4?: string[];
								ipv6?: string[];
							};
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/markup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Render Liquid template */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The Liquid markup(s) to render and an optional set of variables to use in the rendering process. */
			requestBody: {
				content: {
					"application/json": {
						markup: string | string[];
						/**
						 * @example {
						 *       "name": "World"
						 *     }
						 */
						variables: Record<string, never>;
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: string | string[];
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/models": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all device models */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["Model"][];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/palettes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all palettes */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["Palette"][];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/devices": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List my devices */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["Device"][];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/devices/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Device ID */
				id: number;
			};
			cookie?: never;
		};
		/** Get the data of a device */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Device ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["Device"];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update a device */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Device ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						/** @example true */
						sleep_mode_enabled?: boolean;
						/** @example 1320 */
						sleep_start_time?: number;
						/** @example 480 */
						sleep_end_time?: number;
						/** @example 69 */
						percent_charged?: number;
					};
				};
			};
			responses: {
				/** @description Updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		trace?: never;
	};
	"/api/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get my user data */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["User"];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/playlists/items": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List my playlist items */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["PlaylistItem"][];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/playlists/items/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update a playlist item */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description ID of the playlist item */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": {
						visible: boolean;
					};
				};
			};
			responses: {
				/** @description Updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		trace?: never;
	};
	"/api/plugin_settings/{id}/archive": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
				id: string;
			};
			cookie?: never;
		};
		/**
		 * Download a plugin setting archive
		 * @description Numeric IDs require bearer auth. UUIDs act as capability URLs and may
		 *     be called without authentication.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["PluginSettingArchive"];
						};
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Unprocessable Entity */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		/** Upload a plugin setting archive */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
					id: string;
				};
				cookie?: never;
			};
			/** @description Plugin setting archive file */
			requestBody: {
				content: {
					"multipart/form-data": {
						/** Format: binary */
						file?: string;
						/** Format: binary */
						archive?: string;
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["PluginSettingArchive"];
						};
					};
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Archive too large or invalid */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/plugin_settings/{id}/data": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
				id: string;
			};
			cookie?: never;
		};
		/**
		 * Get the data of a plugin setting
		 * @description Numeric IDs require bearer auth. UUIDs act as capability URLs and may
		 *     be called without authentication — knowing the UUID is sufficient.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: {
								[key: string]: unknown;
							};
						};
					};
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Database unavailable */
				503: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		/**
		 * Update data for a plugin setting
		 * @description Numeric IDs require bearer auth. UUIDs act as capability URLs and may
		 *     be called without authentication — this is the TRMNL webhook contract.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
					id: string;
				};
				cookie?: never;
			};
			/** @description The value of `merge_variables` must be a JSON object */
			requestBody: {
				content: {
					"application/json": components["schemas"]["PluginSettingDataParams"];
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: {
								[key: string]: unknown;
							};
						};
					};
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Data cannot be modified */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/plugin_settings/{id}/image": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
				id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Upload an image icon for a plugin setting
		 * @description Multipart upload of a raster image (PNG/JPEG/WebP/GIF). The bytes are
		 *     stored inline as a `data:` URL in `icon_url`. SVG is rejected because
		 *     a script-bearing SVG inside a `data:` URL becomes XSS as soon as a
		 *     client renders it outside a strictly inert path.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL — no auth) */
					id: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"multipart/form-data": {
						/** Format: binary */
						image?: string;
						/** Format: binary */
						file?: string;
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: {
								icon_url?: string | null;
								icon_content_type?: string | null;
							};
						};
					};
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Image too large or unrecognized format */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/plugin_settings/{id}/markup/{size}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read markup for a size */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL) */
					id: string;
					/** @description Markup size (markup_full, markup_quadrant, markup_half_horizontal, markup_half_vertical) */
					size: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns markup content (text/plain) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Invalid size */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		/** Write markup for a size */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL) */
					id: string;
					/** @description Markup size (markup_full, markup_quadrant, markup_half_horizontal, markup_half_vertical) */
					size: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": {
						content: string;
					};
				};
			};
			responses: {
				/** @description Markup written successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Invalid size or oversized content */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/plugin_settings/{id}/settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update plugin settings fields */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL) */
					id: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": {
						fields: {
							[key: string]: string | null;
						};
					};
				};
			};
			responses: {
				/** @description Settings updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Non-string field values */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		trace?: never;
	};
	"/api/plugin_settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List my plugin settings */
		get: {
			parameters: {
				query?: {
					/** @description ID of a plugin or "calendars" to filter calendar plugins */
					plugin_id?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns all calendar plugin settings except Google Calendar */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["PluginSetting"][];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		put?: never;
		/** Create a new plugin setting */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["PluginSettingParams"];
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							data?: components["schemas"]["PluginSetting"];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Unprocessable Entity */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/plugin_settings/{id}/details": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get plugin setting details */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL) */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns plugin details with markup sizes */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/plugin_settings/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete a plugin setting */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Plugin setting numeric ID (requires auth) or UUID (capability URL) */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized (numeric id without session) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Error: {
			/** @example An error occurred */
			error?: string;
		};
		Device: {
			/** @example 123 */
			id?: number;
			/** @example My TRMNL */
			name?: string;
			/** @example ABC-123 */
			friendly_id?: string;
			/** @example 12:34:56:78:9A:BC */
			mac_address?: string;
			/** @example 3.7 */
			battery_voltage?: number | null;
			/** @example -70 */
			rssi?: number | null;
			/** @example false */
			sleep_mode_enabled?: boolean;
			/** @example 1320 */
			sleep_start_time?: number;
			/** @example 480 */
			sleep_end_time?: number;
			/**
			 * Format: date_time
			 * @example 2026-03-31T14:30:00.000Z
			 */
			last_ping_at?: string | null;
			/**
			 * Format: date_time
			 * @example 2026-03-31T14:30:00.000Z
			 */
			hardware_last_ping_at?: string | null;
			/** @example 85 */
			percent_charged?: number;
			/** @example 75 */
			wifi_strength?: number;
		};
		Model: {
			/**
			 * @description Unique identifier
			 * @example trmnl_original
			 */
			name?: string;
			/**
			 * @description Human-readable name
			 * @example TRMNL
			 */
			label?: string;
			/**
			 * @description Description
			 * @example Original TRMNL model
			 */
			description?: string;
			/**
			 * @description Screen width in pixels
			 * @example 800
			 */
			width?: number;
			/**
			 * @description Screen height in pixels
			 * @example 480
			 */
			height?: number;
			/**
			 * @description Number of colors supported
			 * @example 2
			 */
			colors?: number;
			/**
			 * @description Color bit depth
			 * @example 1
			 */
			bit_depth?: number;
			/**
			 * @description Display scale factor
			 * @example 1
			 */
			scale_factor?: number;
			/**
			 * @description Screen rotation in degrees
			 * @example 90
			 */
			rotation?: number;
			/**
			 * @description Image MIME type
			 * @example image/png
			 */
			mime_type?: string;
			/**
			 * @description X offset for image rendering
			 * @example 10
			 */
			offset_x?: number;
			/**
			 * @description Y offset for image rendering
			 * @example 20
			 */
			offset_y?: number;
			/**
			 * @description Device kind (e.g., trmnl, kindle, byod)
			 * @example trmnl
			 * @enum {string}
			 */
			kind?: "trmnl" | "kindle" | "byod" | "tidbyt";
			/**
			 * @description Supported color palette IDs
			 * @example [
			 *       "bw",
			 *       "gray-4",
			 *       "gray-16"
			 *     ]
			 */
			palette_ids?: string[];
			/**
			 * @description Preview white point mode for color previews
			 * @example true_white
			 * @enum {string}
			 */
			preview_white_point?: "true_white" | "limited";
			/**
			 * @description Maximum image file size in bytes for webhook uploads
			 * @example 92160
			 */
			image_size_limit?: number;
			/**
			 * @description Whether webhook image uploads are supported for this device type
			 * @example true
			 */
			image_upload_supported?: boolean;
			/** @description CSS classes and variables for web rendering */
			css?: {
				classes?: {
					/** @example screen--og_plus */
					device?: string;
					/** @example screen--md */
					size?: string;
					/** @example screen--density-1x */
					density?: string;
				};
				variables?: string[][];
			} | null;
		};
		Palette: {
			/**
			 * @description Unique identifier
			 * @example gray-16
			 */
			id?: string;
			/**
			 * @description Human-readable name
			 * @example 16-Gray
			 */
			name?: string;
			/**
			 * @description Number of grayscale levels (null for color palettes)
			 * @example 16
			 */
			grays?: number | null;
			/**
			 * @description Array of hex color codes (null for grayscale palettes)
			 * @example [
			 *       "#FF0000",
			 *       "#00FF00",
			 *       "#0000FF",
			 *       "#FFFF00",
			 *       "#000000",
			 *       "#FFFFFF"
			 *     ]
			 */
			colors?: string[] | null;
			/**
			 * @description Framework CSS class for this palette
			 * @example screen--4bit
			 */
			framework_class?: string;
			/**
			 * @description For color palettes, bit depth for grayscale areas (1 for 3/4-color limited, 2 for 6/7-color, 4 for full-spectrum)
			 * @example 1
			 */
			grayscale_bit_depth?: number | null;
		};
		PlaylistItem: {
			/**
			 * Format: date_time
			 * @example 2023-10-01T12:00:00Z
			 */
			created_at?: string;
			/** @example 1 */
			device_id?: number;
			/** @example 1 */
			id?: number;
			/** @example 1 */
			mashup_id?: number | null;
			/** @example true */
			mirror?: boolean;
			/** @example 1 */
			playlist_group_id?: number;
			plugin_setting?: components["schemas"]["PluginSetting"];
			/** @example 1 */
			plugin_setting_id?: number;
			/**
			 * Format: date_time
			 * @example 2023-10-01T12:00:00Z
			 */
			rendered_at?: string;
			/** @example 1 */
			row_order?: number;
			/**
			 * Format: date_time
			 * @example 2023-10-01T12:00:00Z
			 */
			updated_at?: string;
			/** @example true */
			visible?: boolean;
		};
		PlaylistItemParams: {
			/** @example true */
			visible?: boolean;
		};
		PluginSetting: {
			/** @example 1 */
			id?: number;
			/** @example My Plugin Setting */
			name?: string;
			/** @example 1 */
			plugin_id?: number;
			/** @example https://trmnl-public.s3.com/qwertyasdf */
			icon_url?: string | null;
			/** @example image/png */
			icon_content_type?: string | null;
			/** @example false */
			"read_only?"?: boolean;
			/** @example webhook */
			strategy?: string | null;
		};
		PluginSettingArchive: {
			/** @description YAML settings file */
			settings_yaml?: string;
		};
		PluginSettingParams: {
			/** @example My Plugin Setting */
			name?: string;
			/** @example 1 */
			plugin_id?: number;
		};
		PluginSettingDataParams: {
			/** @description Arbitrary JSON object merged into the plugin setting's `merge_variables` (whole-replace). */
			merge_variables: {
				[key: string]: unknown;
			};
		};
		User: {
			/** @example 42 */
			id?: number;
			/** @example Jim Bob */
			name?: string;
			/** @example jimbob@gmail.net */
			email?: string;
			/** @example Jim */
			first_name?: string;
			/** @example Bob */
			last_name?: string;
			/** @example en */
			locale?: string;
			/** @example Eastern Time (US & Canada) */
			time_zone?: string;
			/** @example America/New_York */
			time_zone_iana?: string;
			/** @example -14400 */
			utc_offset?: number;
			/** @example user_xxxxxx */
			api_key?: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
